vim.pack.add({
    { src = "https://github.com/rose-pine/neovim" },
    { src = "https://github.com/xiyaowong/transparent.nvim" },
    { src = "https://github.com/stevearc/oil.nvim" },
    { src = "https://github.com/echasnovski/mini.pick" },
    { src = "https://github.com/echasnovski/mini.extra" },
    { src = "https://github.com/nvim-treesitter/nvim-treesitter" },
    { src = "https://github.com/nvim-treesitter/nvim-treesitter-context" },
    { src = "https://github.com/neovim/nvim-lspconfig" },
    { src = "https://github.com/prettier/vim-prettier" },
    { src = "https://github.com/hrsh7th/nvim-cmp" },
    { src = "https://github.com/hrsh7th/cmp-nvim-lsp" },
    { src = "https://github.com/hrsh7th/cmp-buffer" },
    { src = "https://github.com/hrsh7th/cmp-path" },
    { src = "https://github.com/saadparwaiz1/cmp_luasnip" },
    { src = "https://github.com/L3MON4D3/LuaSnip" },
    { src = "https://github.com/LunarVim/bigfile.nvim" },
    { src = "https://github.com/rafamadriz/friendly-snippets" },
    { src = "https://github.com/lewis6991/gitsigns.nvim" },
    { src = "https://github.com/nvim-lua/plenary.nvim" },
    { src = "https://github.com/theprimeagen/harpoon", version = "harpoon2" },
    { src = "https://github.com/ThePrimeagen/99" },
    { src = "https://github.com/nickjvandyke/opencode.nvim" },
    { src = "https://github.com/jackplus-xyz/monaspace.nvim" },
    { src = "https://github.com/MeanderingProgrammer/render-markdown.nvim" },
})
